//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/BankService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BankClient.ServiceReference1.UserCalculator> UserCalculationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondName {
            get {
                return this.SecondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondNameField, value) != true)) {
                    this.SecondNameField = value;
                    this.RaisePropertyChanged("SecondName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<BankClient.ServiceReference1.UserCalculator> UserCalculations {
            get {
                return this.UserCalculationsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCalculationsField, value) != true)) {
                    this.UserCalculationsField = value;
                    this.RaisePropertyChanged("UserCalculations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCalculator", Namespace="http://schemas.datacontract.org/2004/07/BankService")]
    [System.SerializableAttribute()]
    public partial class UserCalculator : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BankClient.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserCalculatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationName {
            get {
                return this.OperationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationNameField, value) != true)) {
                    this.OperationNameField = value;
                    this.RaisePropertyChanged("OperationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BankClient.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserCalculatorID {
            get {
                return this.UserCalculatorIDField;
            }
            set {
                if ((this.UserCalculatorIDField.Equals(value) != true)) {
                    this.UserCalculatorIDField = value;
                    this.RaisePropertyChanged("UserCalculatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deposit", Namespace="http://schemas.datacontract.org/2004/07/BankService")]
    [System.SerializableAttribute()]
    public partial class Deposit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepositIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BankClient.ServiceReference1.Rate> RatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepositID {
            get {
                return this.DepositIDField;
            }
            set {
                if ((this.DepositIDField.Equals(value) != true)) {
                    this.DepositIDField = value;
                    this.RaisePropertyChanged("DepositID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Partial {
            get {
                return this.PartialField;
            }
            set {
                if ((object.ReferenceEquals(this.PartialField, value) != true)) {
                    this.PartialField = value;
                    this.RaisePropertyChanged("Partial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<BankClient.ServiceReference1.Rate> Rates {
            get {
                return this.RatesField;
            }
            set {
                if ((object.ReferenceEquals(this.RatesField, value) != true)) {
                    this.RatesField = value;
                    this.RaisePropertyChanged("Rates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rate", Namespace="http://schemas.datacontract.org/2004/07/BankService")]
    [System.SerializableAttribute()]
    public partial class Rate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BankClient.ServiceReference1.Deposit DepositField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepositIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PercentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RateIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BankClient.ServiceReference1.Deposit Deposit {
            get {
                return this.DepositField;
            }
            set {
                if ((object.ReferenceEquals(this.DepositField, value) != true)) {
                    this.DepositField = value;
                    this.RaisePropertyChanged("Deposit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepositID {
            get {
                return this.DepositIDField;
            }
            set {
                if ((this.DepositIDField.Equals(value) != true)) {
                    this.DepositIDField = value;
                    this.RaisePropertyChanged("DepositID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Percents {
            get {
                return this.PercentsField;
            }
            set {
                if ((this.PercentsField.Equals(value) != true)) {
                    this.PercentsField = value;
                    this.RaisePropertyChanged("Percents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RateID {
            get {
                return this.RateIDField;
            }
            set {
                if ((this.RateIDField.Equals(value) != true)) {
                    this.RateIDField = value;
                    this.RaisePropertyChanged("RateID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credit", Namespace="http://schemas.datacontract.org/2004/07/BankService")]
    [System.SerializableAttribute()]
    public partial class Credit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreditIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nLinkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreditID {
            get {
                return this.CreditIDField;
            }
            set {
                if ((this.CreditIDField.Equals(value) != true)) {
                    this.CreditIDField = value;
                    this.RaisePropertyChanged("CreditID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nLink {
            get {
                return this.nLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.nLinkField, value) != true)) {
                    this.nLinkField = value;
                    this.RaisePropertyChanged("nLink");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LogIn", ReplyAction="http://tempuri.org/IService1/LogInResponse")]
        BankClient.ServiceReference1.User LogIn(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LogIn", ReplyAction="http://tempuri.org/IService1/LogInResponse")]
        System.Threading.Tasks.Task<BankClient.ServiceReference1.User> LogInAsync(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCalculator", ReplyAction="http://tempuri.org/IService1/UpdateCalculatorResponse")]
        void UpdateCalculator(BankClient.ServiceReference1.UserCalculator calc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCalculator", ReplyAction="http://tempuri.org/IService1/UpdateCalculatorResponse")]
        System.Threading.Tasks.Task UpdateCalculatorAsync(BankClient.ServiceReference1.UserCalculator calc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        string RegisterUser(BankClient.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        System.Threading.Tasks.Task<string> RegisterUserAsync(BankClient.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllDeposits", ReplyAction="http://tempuri.org/IService1/GetAllDepositsResponse")]
        System.Collections.Generic.List<BankClient.ServiceReference1.Deposit> GetAllDeposits();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllDeposits", ReplyAction="http://tempuri.org/IService1/GetAllDepositsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BankClient.ServiceReference1.Deposit>> GetAllDepositsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllDepositsRates", ReplyAction="http://tempuri.org/IService1/GetAllDepositsRatesResponse")]
        System.Collections.Generic.List<BankClient.ServiceReference1.Rate> GetAllDepositsRates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllDepositsRates", ReplyAction="http://tempuri.org/IService1/GetAllDepositsRatesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BankClient.ServiceReference1.Rate>> GetAllDepositsRatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInfoByUserEmail", ReplyAction="http://tempuri.org/IService1/GetInfoByUserEmailResponse")]
        System.Collections.Generic.List<BankClient.ServiceReference1.UserCalculator> GetInfoByUserEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInfoByUserEmail", ReplyAction="http://tempuri.org/IService1/GetInfoByUserEmailResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BankClient.ServiceReference1.UserCalculator>> GetInfoByUserEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmailsByOperationType", ReplyAction="http://tempuri.org/IService1/GetEmailsByOperationTypeResponse")]
        System.Collections.Generic.List<string> GetEmailsByOperationType(string operationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmailsByOperationType", ReplyAction="http://tempuri.org/IService1/GetEmailsByOperationTypeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetEmailsByOperationTypeAsync(string operationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCredits", ReplyAction="http://tempuri.org/IService1/GetAllCreditsResponse")]
        System.Collections.Generic.List<BankClient.ServiceReference1.Credit> GetAllCredits(string operationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCredits", ReplyAction="http://tempuri.org/IService1/GetAllCreditsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BankClient.ServiceReference1.Credit>> GetAllCreditsAsync(string operationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateCredit", ReplyAction="http://tempuri.org/IService1/CreateCreditResponse")]
        void CreateCredit(BankClient.ServiceReference1.Credit cr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateCredit", ReplyAction="http://tempuri.org/IService1/CreateCreditResponse")]
        System.Threading.Tasks.Task CreateCreditAsync(BankClient.ServiceReference1.Credit cr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateDeposit", ReplyAction="http://tempuri.org/IService1/CreateDepositResponse")]
        void CreateDeposit(BankClient.ServiceReference1.Deposit dep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateDeposit", ReplyAction="http://tempuri.org/IService1/CreateDepositResponse")]
        System.Threading.Tasks.Task CreateDepositAsync(BankClient.ServiceReference1.Deposit dep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserIDByEmail", ReplyAction="http://tempuri.org/IService1/GetUserIDByEmailResponse")]
        int GetUserIDByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserIDByEmail", ReplyAction="http://tempuri.org/IService1/GetUserIDByEmailResponse")]
        System.Threading.Tasks.Task<int> GetUserIDByEmailAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : BankClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<BankClient.ServiceReference1.IService1>, BankClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BankClient.ServiceReference1.User LogIn(string name, string password) {
            return base.Channel.LogIn(name, password);
        }
        
        public System.Threading.Tasks.Task<BankClient.ServiceReference1.User> LogInAsync(string name, string password) {
            return base.Channel.LogInAsync(name, password);
        }
        
        public void UpdateCalculator(BankClient.ServiceReference1.UserCalculator calc) {
            base.Channel.UpdateCalculator(calc);
        }
        
        public System.Threading.Tasks.Task UpdateCalculatorAsync(BankClient.ServiceReference1.UserCalculator calc) {
            return base.Channel.UpdateCalculatorAsync(calc);
        }
        
        public string RegisterUser(BankClient.ServiceReference1.User user) {
            return base.Channel.RegisterUser(user);
        }
        
        public System.Threading.Tasks.Task<string> RegisterUserAsync(BankClient.ServiceReference1.User user) {
            return base.Channel.RegisterUserAsync(user);
        }
        
        public System.Collections.Generic.List<BankClient.ServiceReference1.Deposit> GetAllDeposits() {
            return base.Channel.GetAllDeposits();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BankClient.ServiceReference1.Deposit>> GetAllDepositsAsync() {
            return base.Channel.GetAllDepositsAsync();
        }
        
        public System.Collections.Generic.List<BankClient.ServiceReference1.Rate> GetAllDepositsRates() {
            return base.Channel.GetAllDepositsRates();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BankClient.ServiceReference1.Rate>> GetAllDepositsRatesAsync() {
            return base.Channel.GetAllDepositsRatesAsync();
        }
        
        public System.Collections.Generic.List<BankClient.ServiceReference1.UserCalculator> GetInfoByUserEmail(string email) {
            return base.Channel.GetInfoByUserEmail(email);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BankClient.ServiceReference1.UserCalculator>> GetInfoByUserEmailAsync(string email) {
            return base.Channel.GetInfoByUserEmailAsync(email);
        }
        
        public System.Collections.Generic.List<string> GetEmailsByOperationType(string operationType) {
            return base.Channel.GetEmailsByOperationType(operationType);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetEmailsByOperationTypeAsync(string operationType) {
            return base.Channel.GetEmailsByOperationTypeAsync(operationType);
        }
        
        public System.Collections.Generic.List<BankClient.ServiceReference1.Credit> GetAllCredits(string operationType) {
            return base.Channel.GetAllCredits(operationType);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BankClient.ServiceReference1.Credit>> GetAllCreditsAsync(string operationType) {
            return base.Channel.GetAllCreditsAsync(operationType);
        }
        
        public void CreateCredit(BankClient.ServiceReference1.Credit cr) {
            base.Channel.CreateCredit(cr);
        }
        
        public System.Threading.Tasks.Task CreateCreditAsync(BankClient.ServiceReference1.Credit cr) {
            return base.Channel.CreateCreditAsync(cr);
        }
        
        public void CreateDeposit(BankClient.ServiceReference1.Deposit dep) {
            base.Channel.CreateDeposit(dep);
        }
        
        public System.Threading.Tasks.Task CreateDepositAsync(BankClient.ServiceReference1.Deposit dep) {
            return base.Channel.CreateDepositAsync(dep);
        }
        
        public int GetUserIDByEmail(string email) {
            return base.Channel.GetUserIDByEmail(email);
        }
        
        public System.Threading.Tasks.Task<int> GetUserIDByEmailAsync(string email) {
            return base.Channel.GetUserIDByEmailAsync(email);
        }
    }
}
